### ISSUE TITLE
Wrong Project resources links

### ISSUE THREAD

**Issue by kingosticks** [rawdlite/mopidy-beets-local#1]
The Project resources links in the readme all point to https://github.com/rawdlite/mopidy-beetslocal instead of https://github.com/rawdlite/mopidy-beets-local.  Found when trying to get to the source code from https://pypi.python.org/pypi/Mopidy-BeetsLocal

**Comment by rawdlite** [comment]
Thank you, i will look into this.

**Comment by rawdlite** [comment]
Fixed the Readme to https://github.com/rawdlite/mopidy-beets-local.
